### PR TITLE
Adding static folder and moving the stylesheet there.

### PR DESCRIPTION
**Pull request by ir-3**
**PLEASE TEST THIS BEFORE IMPLEMENTING THIS, XUA!**

I did this at school so I have no way to test it. However, I am 90% sure that this is correct. A static folder is always the way to go for resources that won't change.

See [this](http://flask.pocoo.org/docs/1.0/tutorial/static/) for more information on Flask static files.

### CODE REVIEW

**Comment by crrapi** [comment]
I'm pretty sure `url_for` is for app routes and not files.

**Comment by XuaTheGrate** [comment]
I think I already did this on my local machine lol

**Comment by XuaTheGrate** [comment]
Yep just check, already have this.

**Comment by ir-3** [comment]
Lol, phat rip.

**Pull request closed without merging**
